image:
  registry: registry.cn-beijing.aliyuncs.com
  repository: alphesh-soft
  name: mysql-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "9.5.0-2.2.6"
  pullSecrets:
    enabled: true
    secretName: registry-aliyun

envs:
    imagesPullPolicy: IfNotPresent
    imagesDefaultRegistry:
    imagesDefaultRepository:
    k8sClusterDomain:

replicas: 1

## An example of using affinity for scheduling the operator pods
#affinity:
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#    - labelSelector:
#        matchLabels:
#          ....
#      topologyKey: kubernetes.io/hostname

## An example of using nodeSelector for scheduling the operator pods
#nodeSelector:
#  failure-domain.beta.kubernetes.io/zone: US-ASHBURN-AD-1

# If you would like to debug the Helm output with `helm template`, you need
# to turn disableLookups on as during `helm template` Helm won't contact the kube API
# and all lookups will thus fail
disableLookups: false
debugger:
  enabled: false
  bindip: 0.0.0.0
  bindport: 9009
