version: '3.8'

services:
  mysql56_test:
    image: registry.cn-beijing.aliyuncs.com/alphesh-soft/mysql:5.6.36
    container_name: mysql56_test
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=alphesh123
      - TZ=Asia/Shanghai
    ports:
      - "3305:3306"
    volumes:
      - /alphesh/data/mysql5_test:/var/lib/mysql
      - /alphesh/soft/mysql5_test/conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - /alphesh/logs/mysql5_test:/var/log/mysql
    deploy:
      resources:
        limits:
          memory: 4G